[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "grandfep"
version = "2.0.0_dev"
description = "GrandFEP: A set of enhanced sampling for FEP"
authors = [
    { name = "Chenggong Hui"}
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "openmm",
    "rdkit",

]

[project.optional-dependencies]
chem = ["rdkit"]
dev = ["pytest",]
GUI = [
    "httpx",
    "fastapi>=0.110",
    "uvicorn[standard]>=0.29",
    "jinja2>=3.1",
    "python-multipart>=0.0.9",
]

[tool.setuptools.packages.find]
where = ["src"]

